#! /usr/bin/env bash
PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`

# Get a list of all files staged for commit
STAGED_FILES=$(git diff --cached --name-only)

# Function to check if staged files are modified
check_staged_files() {
    for FILE in $STAGED_FILES; do
        if [[ $(git diff --name-only "$FILE") ]]; then
            echo "File $FILE was modified by the linting script."
            echo "Please add the changes to your commit."
            return 1
        fi
    done
    return 0
}

# Check and run npm 'lint:fix' script
if [ -f "$PROJECT/package.json" ] && grep -q '"lint:fix":' "$PROJECT/package.json"; then
    echo "Running npm 'lint:fix' script..."
    ddev npm run lint:fix
    if [ $? != 0 ]; then
        echo "npm 'lint:fix' script failed. Fix the error before commit."
        exit 1
    fi
    check_staged_files
    if [ $? != 0 ]; then
        exit 1
    fi
else
    echo "npm 'lint:fix' script not found in package.json. Skipping..."
fi

# Check and run Composer 'fix' script
if [ -f "$PROJECT/composer.json" ] && grep -q '"fix":' "$PROJECT/composer.json"; then
    echo "Running Composer 'fix' script..."
    ddev composer run fix
    if [ $? != 0 ]; then
        echo "Composer 'fix' script failed. Fix the error before commit."
        exit 1
    fi
    check_staged_files
    if [ $? != 0 ]; then
        exit 1
    fi
else
    echo "Composer 'fix' script not found in composer.json. Skipping..."
fi

exit 0
